import os
from typing import Dict, Any, List
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

# ----------------- DOCX Exporter -----------------

def export_to_docx(data: Dict[str, Any], file_path: str):
    """Exports research report data to a styled DOCX file."""
    doc = Document()
    
    # Page setup
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)
        
    # Styles config
    styles = doc.styles
    
    # Title Styling
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    title_run = title_p.add_run(f"Research Report: {data['question']}")
    title_run.font.name = "Arial"
    title_run.font.size = Pt(22)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(31, 78, 121) # Sleek navy
    
    # Subtitle
    sub_p = doc.add_paragraph()
    sub_run = sub_p.add_run("Generated by PageRAG AI Research System\nDate: 2026-06-25")
    sub_run.font.name = "Arial"
    sub_run.font.size = Pt(11)
    sub_run.font.italic = True
    sub_run.font.color.rgb = RGBColor(100, 100, 100)
    
    # Border line
    doc.add_paragraph("__________________________________________________________________")
    doc.add_paragraph()
    
    # 1. Executive Summary
    h1 = doc.add_paragraph()
    h1_run = h1.add_run("1. Executive Summary")
    h1_run.font.name = "Arial"
    h1_run.font.size = Pt(14)
    h1_run.font.bold = True
    h1_run.font.color.rgb = RGBColor(31, 78, 121)
    
    p1 = doc.add_paragraph()
    p1_run = p1.add_run(data["summary"])
    p1_run.font.name = "Arial"
    p1_run.font.size = Pt(11)
    
    doc.add_paragraph()
    
    # 2. Key Findings
    h2 = doc.add_paragraph()
    h2_run = h2.add_run("2. Key Findings & Supporting Evidence")
    h2_run.font.name = "Arial"
    h2_run.font.size = Pt(14)
    h2_run.font.bold = True
    h2_run.font.color.rgb = RGBColor(31, 78, 121)
    
    for idx, c in enumerate(data.get("claims", []), 1):
        cit_str = ", ".join(f"[{i}]" for i in c["citation_indices"])
        cp = doc.add_paragraph()
        cp_run = cp.add_run(f"Finding {idx}: {c['claim']} {cit_str}")
        cp_run.font.name = "Arial"
        cp_run.font.size = Pt(12)
        cp_run.font.bold = True
        
        ep = doc.add_paragraph()
        ep.paragraph_format.left_indent = Inches(0.25)
        ep_run = ep.add_run(f"Evidence: \"{c['evidence']}\"")
        ep_run.font.name = "Arial"
        ep_run.font.size = Pt(10.5)
        ep_run.font.italic = True
        ep_run.font.color.rgb = RGBColor(80, 80, 80)
        
    doc.add_paragraph()
    
    # 3. Comprehensive Synthesis
    h3 = doc.add_paragraph()
    h3_run = h3.add_run("3. Detailed Synthesis")
    h3_run.font.name = "Arial"
    h3_run.font.size = Pt(14)
    h3_run.font.bold = True
    h3_run.font.color.rgb = RGBColor(31, 78, 121)
    
    # Process basic markdown paragraphs
    paragraphs = data["answer"].split("\n\n")
    for para in paragraphs:
        if para.strip():
            # Filter headers inside answer if any
            if para.strip().startswith("###"):
                p_text = para.replace("###", "").strip()
                p = doc.add_paragraph()
                r = p.add_run(p_text)
                r.font.name = "Arial"
                r.font.size = Pt(12)
                r.font.bold = True
            elif para.strip().startswith("##"):
                p_text = para.replace("##", "").strip()
                p = doc.add_paragraph()
                r = p.add_run(p_text)
                r.font.name = "Arial"
                r.font.size = Pt(13)
                r.font.bold = True
            elif para.strip().startswith("*"):
                p = doc.add_paragraph(style='List Bullet')
                p_text = para.replace("*", "").strip()
                r = p.add_run(p_text)
                r.font.name = "Arial"
                r.font.size = Pt(11)
            else:
                p = doc.add_paragraph()
                r = p.add_run(para.strip())
                r.font.name = "Arial"
                r.font.size = Pt(11)
                
    doc.add_paragraph()
    
    # 4. Disagreements and Nuances
    h4 = doc.add_paragraph()
    h4_run = h4.add_run("4. Disagreements and Nuances")
    h4_run.font.name = "Arial"
    h4_run.font.size = Pt(14)
    h4_run.font.bold = True
    h4_run.font.color.rgb = RGBColor(31, 78, 121)
    
    contradictions = data.get("contradictions", [])
    if not contradictions:
        p = doc.add_paragraph()
        r = p.add_run("No major contradictions or disagreements were identified in the corpus.")
        r.font.name = "Arial"
        r.font.size = Pt(11)
        r.font.italic = True
    else:
        for idx, con in enumerate(contradictions, 1):
            ref_a = ", ".join(f"[{i}]" for i in con["citation_indices_a"])
            ref_b = ", ".join(f"[{i}]" for i in con["citation_indices_b"])
            
            cp = doc.add_paragraph()
            r = cp.add_run(f"Disagreement {idx}: {con['topic']}")
            r.font.name = "Arial"
            r.font.size = Pt(12)
            r.font.bold = True
            
            p_a = doc.add_paragraph()
            p_a.paragraph_format.left_indent = Inches(0.25)
            r_a = p_a.add_run(f"Position A: {con['finding_a']} {ref_a}")
            r_a.font.name = "Arial"
            r_a.font.size = Pt(10.5)
            
            p_b = doc.add_paragraph()
            p_b.paragraph_format.left_indent = Inches(0.25)
            r_b = p_b.add_run(f"Position B: {con['finding_b']} {ref_b}")
            r_b.font.name = "Arial"
            r_b.font.size = Pt(10.5)
            
            p_res = doc.add_paragraph()
            p_res.paragraph_format.left_indent = Inches(0.25)
            r_res = p_res.add_run(f"Resolution/Context: {con['explanation']}")
            r_res.font.name = "Arial"
            r_res.font.size = Pt(10.5)
            r_res.font.italic = True
            r_res.font.color.rgb = RGBColor(100, 100, 100)
            
    doc.add_paragraph()
    
    # 5. References
    h5 = doc.add_paragraph()
    h5_run = h5.add_run("5. References")
    h5_run.font.name = "Arial"
    h5_run.font.size = Pt(14)
    h5_run.font.bold = True
    h5_run.font.color.rgb = RGBColor(31, 78, 121)
    
    for ref in data.get("citations", []):
        ref_p = doc.add_paragraph()
        authors = ref["authors"] or "Unknown"
        ref_run = ref_p.add_run(f"[{ref['citation_index']}] {ref['title']}. Authors: {authors} ({ref['year']}). Page {ref['page_no']}.")
        ref_run.font.name = "Arial"
        ref_run.font.size = Pt(10)
        
    doc.save(file_path)


# ----------------- PDF Exporter -----------------

class NumberedCanvas(canvas.Canvas):
    """Custom canvas to compute page numbers dynamically."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super().showPage()
        super().save()

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#666666"))
        
        # Draw header
        self.setLineWidth(0.5)
        self.setStrokeColor(colors.HexColor("#CCCCCC"))
        self.line(54, 750, 558, 750)
        self.drawString(54, 755, "PageRAG Research Assistant - Synthesis Report")
        
        # Draw footer
        self.line(54, 50, 558, 50)
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 38, page_text)
        self.drawString(54, 38, "Confidential - Academic & Research Use Only")
        self.restoreState()


def export_to_pdf(data: Dict[str, Any], file_path: str):
    """Exports research report data to a styled PDF file using ReportLab."""
    # Margins setup (54 pt = 0.75 in)
    doc = SimpleDocTemplate(
        file_path,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=72,
        bottomMargin=72
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        name="ReportTitle",
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#1F4E79"),
        spaceAfter=15
    )
    
    meta_style = ParagraphStyle(
        name="ReportMeta",
        fontName="Helvetica-Oblique",
        fontSize=10,
        leading=13,
        textColor=colors.HexColor("#666666"),
        spaceAfter=25
    )
    
    h1_style = ParagraphStyle(
        name="SectionHeader",
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#1F4E79"),
        spaceBefore=15,
        spaceAfter=10,
        keepWithNext=True
    )
    
    h2_style = ParagraphStyle(
        name="SubSectionHeader",
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#333333"),
        spaceBefore=10,
        spaceAfter=6,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        name="ReportBody",
        fontName="Helvetica",
        fontSize=10,
        leading=14.5,
        textColor=colors.HexColor("#333333"),
        spaceAfter=10
    )
    
    quote_style = ParagraphStyle(
        name="EvidenceQuote",
        fontName="Helvetica-Oblique",
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor("#555555"),
        leftIndent=20,
        spaceAfter=8
    )
    
    ref_style = ParagraphStyle(
        name="ReferenceItem",
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#444444"),
        leftIndent=15,
        firstLineIndent=-15,
        spaceAfter=6
    )

    story = []
    
    # Title
    story.append(Paragraph(f"Research Report: {data['question']}", title_style))
    story.append(Paragraph("Generated by PageRAG AI Research System &bull; Date: 2026-06-25", meta_style))
    story.append(Spacer(1, 10))
    
    # 1. Executive Summary
    story.append(Paragraph("1. Executive Summary", h1_style))
    story.append(Paragraph(data["summary"], body_style))
    story.append(Spacer(1, 10))
    
    # 2. Key Findings
    story.append(Paragraph("2. Key Findings & Supporting Evidence", h1_style))
    for idx, c in enumerate(data.get("claims", []), 1):
        cit_str = ", ".join(f"[{i}]" for i in c["citation_indices"])
        story.append(Paragraph(f"Finding {idx}: {c['claim']} <font color='#1F4E79'><b>{cit_str}</b></font>", h2_style))
        story.append(Paragraph(f"&ldquo;{c['evidence']}&rdquo;", quote_style))
    story.append(Spacer(1, 10))
    
    # 3. Detailed Synthesis
    story.append(Paragraph("3. Detailed Synthesis", h1_style))
    paragraphs = data["answer"].split("\n\n")
    for para in paragraphs:
        if para.strip():
            text = para.strip()
            # Basic markdown headings conversion to HTML tags for reportlab
            if text.startswith("###"):
                text_clean = text.replace("###", "").strip()
                story.append(Paragraph(text_clean, h2_style))
            elif text.startswith("##"):
                text_clean = text.replace("##", "").strip()
                story.append(Paragraph(text_clean, h2_style))
            elif text.startswith("*"):
                text_clean = text.replace("*", "").strip()
                bullet_str = f"&bull; {text_clean}"
                story.append(Paragraph(bullet_str, body_style))
            else:
                story.append(Paragraph(text, body_style))
    story.append(Spacer(1, 10))
    
    # 4. Disagreements and Nuances
    story.append(Paragraph("4. Disagreements and Nuances", h1_style))
    contradictions = data.get("contradictions", [])
    if not contradictions:
        story.append(Paragraph("<i>No major direct contradictions or disagreements were identified in the corpus.</i>", body_style))
    else:
        for idx, con in enumerate(contradictions, 1):
            ref_a = ", ".join(f"[{i}]" for i in con["citation_indices_a"])
            ref_b = ", ".join(f"[{i}]" for i in con["citation_indices_b"])
            story.append(Paragraph(f"Disagreement {idx}: {con['topic']}", h2_style))
            story.append(Paragraph(f"<b>Position A:</b> {con['finding_a']} <font color='#1F4E79'><b>{ref_a}</b></font>", body_style))
            story.append(Paragraph(f"<b>Position B:</b> {con['finding_b']} <font color='#1F4E79'><b>{ref_b}</b></font>", body_style))
            story.append(Paragraph(f"<i>Resolution/Nuance:</i> {con['explanation']}", quote_style))
    story.append(Spacer(1, 10))
    
    # 5. References (Keep Together as much as possible)
    ref_flowables = [Paragraph("5. References", h1_style)]
    for ref in data.get("citations", []):
        authors = ref["authors"] or "Unknown"
        ref_text = f"[{ref['citation_index']}] {ref['title']}. Authors: {authors} ({ref['year']}). Page {ref['page_no']}."
        ref_flowables.append(Paragraph(ref_text, ref_style))
        
    story.append(KeepTogether(ref_flowables))
    
    # Build document
    doc.build(story, canvasmaker=NumberedCanvas)
